name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # This will run on Node.js 20 by default

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2 # This will also use Node.js 20

    - name: Log in to Amazon ECR
      run: echo "${{ secrets.AWS_SECRET_ACCESS_KEY }}" | docker login --username AWS --password-stdin 466670870088.dkr.ecr.us-east-1.amazonaws.com

    - name: Build Docker image
      run: docker build -t my-app:latest .

    - name: Tag Docker image
      run: docker tag my-app:latest 466670870088.dkr.ecr.us-east-1.amazonaws.com/my-app-ecr:latest

    - name: Push Docker image to ECR
      run: docker push 466670870088.dkr.ecr.us-east-1.amazonaws.com/my-app-ecr:latest
